"""service config knowledge base fields

Revision ID: 562c9adccffb
Revises: 9aa4493d2167
Create Date: 2026-08-10 11:22:03.912625
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '562c9adccffb'
down_revision: str | None = '9aa4493d2167'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default="" so the NOT NULL add succeeds on any existing v0.15 rows.
    op.add_column(
        'service_configs',
        sa.Column('knowledge_base', sa.String(length=200), nullable=False, server_default=''),
    )
    op.add_column(
        'service_configs',
        sa.Column('knowledge_source', sa.String(length=200), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_configs', 'knowledge_source')
    op.drop_column('service_configs', 'knowledge_base')
    # ### end Alembic commands ###
