"""service configs

Revision ID: 9aa4493d2167
Revises: ad4285db8a7f
Create Date: 2026-08-10 09:48:17.839191
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9aa4493d2167"
down_revision: str | None = "ad4285db8a7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_configs",
        sa.Column("service_name", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("endpoint", sa.String(length=500), nullable=False),
        sa.Column("api_key_encrypted", sa.Text(), nullable=False),
        sa.Column("model_or_deployment", sa.String(length=100), nullable=False),
        sa.Column("default_project", sa.String(length=200), nullable=False),
        sa.Column("is_master", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_configs_service_name"), "service_configs", ["service_name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_configs_service_name"), table_name="service_configs")
    op.drop_table("service_configs")
    # ### end Alembic commands ###
