"""interviewer personas

Revision ID: b0fdc500f6d5
Revises: da25e7365d9a
Create Date: 2026-08-08 12:09:59.754214
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b0fdc500f6d5"
down_revision: str | None = "da25e7365d9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interviewer_personas",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("character", sa.Text(), nullable=False),
        sa.Column("style", sa.Text(), nullable=False),
        sa.Column("prompt_fragment", sa.Text(), nullable=False),
        sa.Column("voice_map", sa.Text(), nullable=False),
        sa.Column("greeting_map", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("turn_detection", sa.String(length=64), nullable=False),
        sa.Column("eou_detection", sa.Boolean(), nullable=False),
        sa.Column("noise_suppression", sa.Boolean(), nullable=False),
        sa.Column("echo_cancellation", sa.Boolean(), nullable=False),
        sa.Column("interim_response", sa.Boolean(), nullable=False),
        sa.Column("proactive_engagement", sa.Boolean(), nullable=False),
        sa.Column("voice_temperature", sa.Float(), nullable=False),
        sa.Column("playback_speed", sa.Float(), nullable=False),
        sa.Column("agent_id", sa.String(length=255), nullable=True),
        sa.Column("agent_version", sa.String(length=64), nullable=True),
        sa.Column("agent_sync_status", sa.String(length=16), nullable=False),
        sa.Column("agent_sync_error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_one_enabled_default_persona",
        "interviewer_personas",
        ["is_default"],
        unique=True,
        sqlite_where=sa.text("enabled = 1 AND is_default = 1"),
        postgresql_where=sa.text("enabled = true AND is_default = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_one_enabled_default_persona",
        table_name="interviewer_personas",
        sqlite_where=sa.text("enabled = 1 AND is_default = 1"),
        postgresql_where=sa.text("enabled = true AND is_default = true"),
    )
    op.drop_table("interviewer_personas")
    # ### end Alembic commands ###
