"""question banks and questions

Revision ID: b78350860f50
Revises: b0fdc500f6d5
Create Date: 2026-08-09 12:48:06.982583
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b78350860f50'
down_revision: str | None = 'b0fdc500f6d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_banks',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_one_enabled_default_bank', 'question_banks', ['is_default'], unique=True, sqlite_where=sa.text('enabled = 1 AND is_default = 1'), postgresql_where=sa.text('enabled = true AND is_default = true'))
    op.create_table('questions',
    sa.Column('bank_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('expected_points', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_follow_ups', sa.Integer(), nullable=False),
    sa.Column('follow_up_prompt', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['question_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_bank_id'), 'questions', ['bank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_bank_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index('uq_one_enabled_default_bank', table_name='question_banks', sqlite_where=sa.text('enabled = 1 AND is_default = 1'), postgresql_where=sa.text('enabled = true AND is_default = true'))
    op.drop_table('question_banks')
    # ### end Alembic commands ###
