/**
 * Does the avatar's mouth actually follow the MODEL's words? Record it and look.
 *
 * This is the one question the instrumented probes could not close. Frames flow on a realtime
 * session (`avatar-speak-start-live` measures exactly when they start), but the server also renders
 * an idle animation, so "frames are arriving" is not "the mouth is saying these words". A frame
 * counter cannot tell those apart; an eye can. An aiortc attempt to pull the stream outside the
 * browser was abandoned rather than trusted — ICE stalled at `checking` with zero frames even in the
 * control, so the apparatus proved nothing either way.
 *
 * So this spec records what the browser itself renders and plays: the avatar's own WebRTC video
 * track plus its audio track, muxed by `MediaRecorder` into one webm with the two in lockstep. No
 * screen recording, no OS audio capture, no extra permission — the tracks come straight off the peer
 * connection, which is also why the file is evidence rather than a re-encode of a re-encode.
 *
 * Why the persona Playground and not an interview: in the Playground **every** assistant turn is
 * generated by the model. The interview deliberately reads bank questions through
 * `pre_generated_assistant_message` (verbatim, TTS, bypassing the brain), so a video recorded there
 * would answer a different question than the one being asked. Here the fake microphone plays a WAV,
 * the model hears it and answers in its own words, and the words it chose are printed next to the
 * file so the recording can be checked against them.
 *
 * Run (needs the real dev servers on :5173/:8000 and real Foundry credentials):
 *
 *   LIVE_VOICE=1 LIPSYNC_LOCALE=zh-CN FAKE_AUDIO=/tmp/az_zh_pause.wav \
 *     npx playwright test avatar-lipsync-record --config=e2e/live.config.ts
 *
 * One avatar session per run, and avatar creation is rate-limited to ~3 per 60 s (measured), so
 * leave a pause between the two locales.
 */
import fs from "node:fs";
import path from "node:path";
import url from "node:url";

import { expect, test } from "@playwright/test";
import { enterVoiceChannel, primeCandidateLogin, waitForInterviewStage } from "./helpers/candidateLogin";

const OUT_DIR = path.join(path.dirname(url.fileURLToPath(import.meta.url)), "output");

const LIVE = process.env.LIVE_VOICE === "1";
const BASE = process.env.BASE || "http://localhost:5173";
const LOCALE = process.env.LIPSYNC_LOCALE === "zh-CN" ? "zh-CN" : "en-US";
/** Long enough for one full model turn to be heard, short enough that the blob crosses the bridge. */
const RECORD_MS = Number(process.env.LIPSYNC_RECORD_MS ?? 26_000);
/** `interview` records the candidate-facing question read (seconds of continuous speech, which is
 *  what makes lip-sync judgeable by eye); `playground` records a model-generated reply, which is
 *  shorter but proves the words were not scripted. */
const SOURCE = process.env.LIPSYNC_SOURCE === "playground" ? "playground" : "interview";
/** Hold the FIRST question read this many ms longer than the product would, to test whether a
 *  realtime session needs more time after the avatar media connection before it will synthesise.
 *  Measured motivation: of four realtime runs, the only audible one had an 865 ms gap between
 *  `pc_connected` and `read_sent`; the three silent ones were 312-376 ms. Cascaded is audible at
 *  381 ms, so the threshold — if there is one — is realtime's. */
const DELAY_READ_MS = Number(process.env.LIPSYNC_DELAY_READ_MS ?? 0);
const ADMIN_USER = process.env.E2E_ADMIN_USERNAME || "admin";
const ADMIN_PW = process.env.E2E_ADMIN_PASSWORD || "e2e-admin-pw";

interface Recorded {
  base64: string;
  mime: string;
  videoTracks: number;
  audioTracks: number;
  ms: number;
  /** Peak level of the audio ACTUALLY captured — the only honest check that the file has a voice. */
  peak: number;
  /** Peak the audibility gate saw across every assistant tap, for telling "silent file" from "silent session". */
  gatePeak: number;
  /** False when no running AudioContext could be obtained, so `peak` means nothing. */
  measured: boolean;
  /** Sample rates of the taps that existed: 16000 is the mic, the others are assistant playback. */
  taps: number[];
  /** Which source won the audition, and at what level — names the transport carrying the voice. */
  audioSource: string;
}

test.describe("avatar lip-sync recording (real Azure)", () => {
  test.skip(!LIVE, "opt-in: set LIVE_VOICE=1 to run against real Azure");
  test.setTimeout(RECORD_MS + 180_000);

  test(`records the avatar speaking (${SOURCE}, ${LOCALE})`, async ({ page }) => {
    const assistantSaid: string[] = [];
    // Which transport actually carries the reply audio? Count it rather than trust a comment: a
    // `response.audio.delta` frame means the voice arrives as PCM on the WebSocket and is played
    // through WebAudio; none of them means it rides the avatar's WebRTC audio track instead. Two
    // silent takes came out of guessing this wrong.
    let audioDeltaFrames = 0;
    const wsErrors: string[] = [];
    const seenTypes = new Map<string, number>();
    const sentFrames: string[] = [];
    page.on("websocket", (ws) => {
      if (!/voice-live\/ws/.test(ws.url())) return;
      // What the BROWSER sends matters as much as what comes back: "Azure behaves differently" and
      // "we asked for something different" are different findings, and only the sent frames separate
      // them. Audio appends are dropped — there are thousands and they carry no decision.
      ws.on("framesent", (f) => {
        const d = typeof f.payload === "string" ? f.payload : "";
        if (!d || d.includes("input_audio_buffer.append")) return;
        sentFrames.push(d.slice(0, 400));
      });
      ws.on("framereceived", (f) => {
        const d = typeof f.payload === "string" ? f.payload : "";
        if (!d) return;
        if (d.includes('"response.audio.delta"')) audioDeltaFrames += 1;
        try {
          const m = JSON.parse(d) as { type?: string };
          const t = String(m.type ?? "");
          if (t) seenTypes.set(t, (seenTypes.get(t) ?? 0) + 1);
          // A silent avatar with no error frame and a silent avatar that was refused are two
          // different findings, and only the frames can tell them apart.
          if (t.endsWith("error")) wsErrors.push(d.slice(0, 300));
        } catch {
          /* binary audio frame */
        }
      });
    });
    // Capture every peer connection the page builds, so the recording can be backed by the two
    // counters that distinguish a speaking avatar from an idle one (frames decoded, audio energy).
    await page.addInitScript(() => {
      const w = window as unknown as {
        __pcs: RTCPeerConnection[];
        __taps: { stream: MediaStream; rate: number }[];
      };
      w.__pcs = [];
      const OrigPC = window.RTCPeerConnection;
      window.RTCPeerConnection = class extends OrigPC {
        constructor(...args: unknown[]) {
          // @ts-expect-error passthrough
          super(...args);
          w.__pcs.push(this);
        }
      } as unknown as typeof RTCPeerConnection;

      // Tap the page's own audio OUTPUT, not a transport. Measured the hard way: two takes recorded
      // the avatar's inbound WebRTC audio track and both came back with RMS 0 from end to end, while
      // the session was plainly speaking — in this product the reply audio reaches the speakers as
      // PCM over the WebSocket and is scheduled through WebAudio (`useVoiceAudio`), so the RTP track
      // is not where the voice is. Mirroring every connect-to-destination into a
      // MediaStreamAudioDestination captures whatever the viewer actually hears, on either path.
      // {stream, rate}: the MIC AudioContext also reaches `destination`, and a tap that cannot tell
      // the two apart records the CANDIDATE instead of the avatar. `useVoiceAudio` pins the rates —
      // mic 16000, assistant playback 24000 — so the rate is the discriminator.
      w.__taps = [];
      const origConnect = AudioNode.prototype.connect;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      AudioNode.prototype.connect = function (this: AudioNode, dest: any, ...rest: any[]) {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
        const result = origConnect.call(this, dest, ...rest);
        try {
          if (dest instanceof AudioDestinationNode) {
            const ctx = dest.context as AudioContext & { __tap?: MediaStreamAudioDestinationNode };
            if (!ctx.__tap) {
              ctx.__tap = ctx.createMediaStreamDestination();
              w.__taps.push({ stream: ctx.__tap.stream, rate: ctx.sampleRate });
              void ctx.resume().catch(() => undefined);
            }
            origConnect.call(this, ctx.__tap);
          }
        } catch {
          /* a tap that cannot be attached must never break playback */
        }
        return result;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
      } as any;
    });
    if (DELAY_READ_MS > 0) {
      await page.addInitScript((ms) => {
        const origSend = WebSocket.prototype.send;
        let held = false;
        WebSocket.prototype.send = function (this: WebSocket, data: never) {
          if (!held && typeof data === "string" && data.includes("pre_generated_assistant_message")) {
            held = true;
            setTimeout(() => origSend.call(this, data), ms);
            return;
          }
          return origSend.call(this, data);
        };
      }, DELAY_READ_MS);
    }
    page.on("console", (m) => {
      const t = m.text();
      if (/\[avatar-stream\] ontrack|proxy\.connected|realtime_pipeline/.test(t)) console.log(t);
    });

    if (SOURCE === "interview") {
      // The candidate path. The interview takes its voice locale from the UI language
      // (`InterviewPage.tsx`: `locale: i18n.language`), so the language is set before the first load
      // rather than clicked afterwards.
      await primeCandidateLogin(page);
      await page.addInitScript((loc) => localStorage.setItem("i18nextLng", loc), LOCALE);
      await page.goto(`${BASE}/interview`);
      await page.getByRole("button", { name: /开始面试|start interview/i }).click();
      await page.getByRole("button", { name: /我准备好了|i'm ready/i }).click();
      await waitForInterviewStage(page);
      await enterVoiceChannel(page);
    } else {
      // The persona editor has its own login, sharing the admin token.
      await page.goto("/admin/agent");
      const login = page.getByTestId("agent-login");
      if (await login.isVisible().catch(() => false)) {
        await page.getByTestId("agent-username-input").fill(ADMIN_USER);
        await page.getByTestId("agent-password-input").fill(ADMIN_PW);
        await login.click();
      }
      await page.getByTestId("configuration-rail-body").waitFor({ timeout: 45_000 });
      // The Playground reads the locale out of the editor's form state, so switching the dropdown is
      // enough — nothing is saved, and the persona is left exactly as it was found.
      await page.getByTestId("config-language").click();
      await page.getByRole("option", { name: LOCALE }).click();
      await page.getByTestId("playground-voice-toggle").click();
    }

    // --- the spoken words, from whichever surface is rendering them ---------------------------
    const words = () =>
      page
        .locator(SOURCE === "interview" ? '[data-testid="transcript"]' : '[data-testid="playground-log"]')
        .innerText()
        .catch(() => "");

    // --- wait for the avatar's video track ----------------------------------------------------
    const video = page.locator("video").first();
    await expect(video).toBeVisible({ timeout: 90_000 });
    await page.waitForFunction(
      () => {
        for (const v of document.querySelectorAll("video")) {
          const s = (v as HTMLVideoElement).srcObject as MediaStream | null;
          if (s && s.getVideoTracks().length > 0) return true;
        }
        return false;
      },
      undefined,
      { timeout: 120_000 },
    );

    // --- wait until the avatar is AUDIBLE, not merely connected ------------------------------
    // The first take of this recording captured 611 decoded frames and totalAudioEnergy == 0: a
    // connected session rendering its idle animation, with nothing being said. A video like that
    // cannot answer the question it was recorded to answer, so the recording does not start until
    // the energy counter actually moves. totalAudioEnergy and not totalSamplesReceived: comfort
    // noise advances the sample count while leaving energy flat.
    const audible = await page
      .waitForFunction(
        async () => {
          const w = window as unknown as {
            __pcs?: RTCPeerConnection[];
            __taps?: { stream: MediaStream; rate: number }[];
            __tapPeak?: number;
            __tapWatch?: boolean;
          };
          // The assistant-playback tap first: that is where this product's reply audio actually is.
          const assistant = (w.__taps ?? []).filter((t) => t.rate !== 16000);
          if (!w.__tapWatch && assistant.length) {
            w.__tapWatch = true;
            w.__tapPeak = 0;
            const ctx = new AudioContext();
            await ctx.resume().catch(() => undefined);
            const an = ctx.createAnalyser();
            an.fftSize = 2048;
            for (const t of assistant) ctx.createMediaStreamSource(t.stream).connect(an);
            const buf = new Float32Array(an.fftSize);
            setInterval(() => {
              an.getFloatTimeDomainData(buf);
              let sum = 0;
              for (const x of buf) sum += x * x;
              w.__tapPeak = Math.max(w.__tapPeak ?? 0, Math.sqrt(sum / buf.length));
            }, 100);
          }
          if ((w.__tapPeak ?? 0) > 0.01) return true;
          // And the RTP track, for a session that does carry the voice there.
          for (const pc of w.__pcs ?? []) {
            const report = await pc.getStats();
            let energy = 0;
            report.forEach((st: Record<string, number | string>) => {
              if (st.type === "inbound-rtp" && st.kind === "audio") {
                energy += Number(st.totalAudioEnergy ?? 0);
              }
            });
            if (energy > 0.005) return true;
          }
          return false;
        },
        undefined,
        { timeout: 120_000, polling: 250 },
      )
      .then(() => true)
      .catch(() => false);
    console.log(`[lipsync] avatar audible before recording: ${audible}`);

    // --- record the tracks the browser is actually rendering and playing ---------------------
    const recorded: Recorded = await page.evaluate(async (ms) => {
      // `captureStream()` on the ELEMENTS, not the tracks they happen to hold right now: a session
      // that rebuilds its peer connection swaps the track underneath, and a recorder holding the old
      // one keeps writing silence. The first Chinese take was exactly that — 1103 video frames and an
      // audio track whose RMS was 0 from end to end.
      const liveVideo = [...document.querySelectorAll("video")].find((v) => {
        const s = (v as HTMLVideoElement).srcObject as MediaStream | null;
        return !!s && s.getVideoTracks().length > 0;
      }) as HTMLVideoElement;
      const grab = (el: HTMLMediaElement): MediaStream | null => {
        const withCapture = el as HTMLMediaElement & { captureStream?: () => MediaStream };
        try {
          return withCapture.captureStream ? withCapture.captureStream() : null;
        } catch {
          return null;
        }
      };
      const videoStream = grab(liveVideo) ?? (liveVideo.srcObject as MediaStream);
      const tracks: MediaStreamTrack[] = [...videoStream.getVideoTracks()];

      // Audio rides its own hidden <audio> element in avatar mode (useAvatarStream appends it on the
      // audio ontrack), so take the LAST such element — recovery appends a new one and removes the
      // old — and fall back to the video stream's own audio.
      // Record the assistant-playback tap's track AS IS. An earlier version summed everything through
      // a fresh AudioContext and wrote silence: a context created outside a user gesture can sit
      // suspended, and a suspended context's output is digital zero — indistinguishable from "the
      // avatar said nothing". Fewer moving parts, and the track is already a single mixed stream.
      // Pick the source that HAS a voice, by measuring both — do not reason about which transport
      // "should" carry it. Measured on this product: with an avatar the reply rides the WebRTC audio
      // track (`totalAudioEnergy` 0.27 in a cascaded control, zero `response.audio.delta` frames on
      // the WebSocket), while the WebAudio playback context exists but stays silent. Preferring the
      // tap on reasoning alone produced four silent recordings of a session that was speaking.
      const taps = (window as unknown as { __taps?: { stream: MediaStream; rate: number }[] }).__taps ?? [];
      const candidates: { label: string; tracks: MediaStreamTrack[] }[] = [];
      for (const a of [...document.querySelectorAll("audio")].reverse()) {
        const st = (a as HTMLAudioElement).srcObject as MediaStream | null;
        if (st?.getAudioTracks().length) candidates.push({ label: "rtp-audio-el", tracks: st.getAudioTracks() });
      }
      if (videoStream.getAudioTracks().length) {
        candidates.push({ label: "rtp-video-stream", tracks: videoStream.getAudioTracks() });
      }
      for (const t of taps.filter((x) => x.rate !== 16000).reverse()) {
        if (t.stream.getAudioTracks().length) {
          candidates.push({ label: `webaudio-${t.rate}`, tracks: t.stream.getAudioTracks() });
        }
      }
      const probeCtx = new AudioContext();
      await probeCtx.resume().catch(() => undefined);
      const levelOf = async (trs: MediaStreamTrack[]): Promise<number> => {
        if (probeCtx.state !== "running") return 0;
        const an = probeCtx.createAnalyser();
        an.fftSize = 2048;
        const src = probeCtx.createMediaStreamSource(new MediaStream(trs));
        src.connect(an);
        const buf = new Float32Array(an.fftSize);
        let peak = 0;
        for (let i = 0; i < 25; i++) {
          await new Promise((r) => setTimeout(r, 100));
          an.getFloatTimeDomainData(buf);
          let sum = 0;
          for (const x of buf) sum += x * x;
          peak = Math.max(peak, Math.sqrt(sum / buf.length));
        }
        src.disconnect();
        return peak;
      };
      let chosen = candidates[0];
      let chosenLevel = 0;
      for (const c of candidates) {
        const lvl = await levelOf(c.tracks);
        if (lvl > chosenLevel) {
          chosen = c;
          chosenLevel = lvl;
        }
        if (chosenLevel > 0.02) break; // a clear voice; no need to audition the rest
      }
      const audioTracks = chosen ? chosen.tracks : [];
      const audioSource = chosen ? `${chosen.label}@${chosenLevel.toFixed(4)}` : "none";
      tracks.push(...audioTracks);

      const stream = new MediaStream(tracks);

      // Measure the level of the audio that is actually going INTO the recording. A file whose audio
      // is silent looks identical to a working one until it is decoded, and that is a check worth
      // having inside the run rather than afterwards.
      // Measure the chosen track itself, with a context confirmed to be RUNNING — a suspended context
      // outputs digital zero, which reads exactly like "the avatar said nothing".
      let peak = 0;
      let measured = false;
      if (audioTracks.length) {
        const mctx = new AudioContext();
        await mctx.resume().catch(() => undefined);
        if (mctx.state === "running") {
          measured = true;
          const an = mctx.createAnalyser();
          an.fftSize = 2048;
          mctx.createMediaStreamSource(new MediaStream(audioTracks)).connect(an);
          const buf = new Float32Array(an.fftSize);
          const tick = setInterval(() => {
            an.getFloatTimeDomainData(buf);
            let sum = 0;
            for (const x of buf) sum += x * x;
            peak = Math.max(peak, Math.sqrt(sum / buf.length));
          }, 100);
          setTimeout(() => clearInterval(tick), ms);
        }
      }
      const wpeak = window as unknown as { __tapPeak?: number };
      const mime = MediaRecorder.isTypeSupported("video/webm;codecs=vp8,opus")
        ? "video/webm;codecs=vp8,opus"
        : "video/webm";
      const rec = new MediaRecorder(stream, { mimeType: mime, videoBitsPerSecond: 1_200_000 });
      const chunks: Blob[] = [];
      rec.ondataavailable = (e) => {
        if (e.data.size) chunks.push(e.data);
      };
      const started = performance.now();
      rec.start(1000);
      await new Promise<void>((r) => setTimeout(r, ms));
      await new Promise<void>((r) => {
        rec.onstop = () => r();
        rec.stop();
      });
      const blob = new Blob(chunks, { type: mime });
      const buf = new Uint8Array(await blob.arrayBuffer());
      let bin = "";
      for (let i = 0; i < buf.length; i += 0x8000) {
        bin += String.fromCharCode(...buf.subarray(i, i + 0x8000));
      }
      return {
        base64: btoa(bin),
        mime,
        videoTracks: stream.getVideoTracks().length,
        audioTracks: stream.getAudioTracks().length,
        ms: Math.round(performance.now() - started),
        peak: Number(Math.max(peak, chosenLevel).toFixed(5)),
        gatePeak: Number((wpeak.__tapPeak ?? 0).toFixed(5)),
        measured,
        taps: taps.map((t) => t.rate),
        audioSource,
      };
    }, RECORD_MS);

    // --- did the avatar actually move and speak during that window? --------------------------
    const stats = await page.evaluate(async () => {
      const pcs = (window as unknown as { __pcs?: RTCPeerConnection[] }).__pcs ?? [];
      const out = { framesDecoded: 0, audioEnergy: 0, samples: 0 };
      for (const pc of pcs) {
        const report = await pc.getStats();
        report.forEach((s: Record<string, number | string>) => {
          if (s.type !== "inbound-rtp") return;
          if (s.kind === "video") out.framesDecoded += Number(s.framesDecoded ?? 0);
          if (s.kind === "audio") {
            out.audioEnergy += Number(s.totalAudioEnergy ?? 0);
            out.samples += Number(s.totalSamplesReceived ?? 0);
          }
        });
      }
      return out;
    });

    fs.mkdirSync(OUT_DIR, { recursive: true });
    const file = path.join(OUT_DIR, `lipsync-${LOCALE}.webm`);
    fs.writeFileSync(file, Buffer.from(recorded.base64, "base64"));
    // Read the log directly as well: the observer can miss a turn that lands between mutations, and
    // the words are the whole point of the file — without them there is nothing to check the mouth
    // against.
    const logText = await words();
    const transcript = logText || assistantSaid.at(-1) || "";
    fs.writeFileSync(
      path.join(OUT_DIR, `lipsync-${LOCALE}.txt`),
      `locale=${LOCALE}\nfile=${path.basename(file)}\nmime=${recorded.mime}\n` +
        `recorded_ms=${recorded.ms}\nvideo_tracks=${recorded.videoTracks}\n` +
        `recorded_audio_peak=${recorded.peak}\ngate_peak=${recorded.gatePeak}\n` +
        `peak_measured=${recorded.measured}\ntap_rates=${recorded.taps.join(",")}\n` +
        `audio_source=${recorded.audioSource}\nsource=${SOURCE}\n` +
        `read_delayed_ms=${DELAY_READ_MS}\n` +
        `ws_response_audio_delta_frames=${audioDeltaFrames}\n` +
        `ws_errors=${wsErrors.length}\n${wsErrors.map((e) => `  ! ${e}`).join("\n")}\n` +
        `ws_sent_frames=${sentFrames.length}\n${sentFrames.map((f) => `  > ${f}`).join("\n")}\n` +
        `ws_frame_types=\n${[...seenTypes.entries()]
          .sort((a, b) => b[1] - a[1])
          .map(([t, n]) => `  ${n.toString().padStart(5)}  ${t}`)
          .join("\n")}\n` +
        `audio_tracks=${recorded.audioTracks}\nframes_decoded=${stats.framesDecoded}\n` +
        `audio_energy=${stats.audioEnergy}\nsamples=${stats.samples}\n\n` +
        `--- what the Playground log held at the end (the model's own words) ---\n${transcript}\n`,
    );

    console.log(
      `\nLIP-SYNC RECORDING (${LOCALE})\n  file           ${file}\n` +
        `  size           ${(fs.statSync(file).size / 1024).toFixed(0)} KiB\n` +
        `  tracks         video=${recorded.videoTracks} audio=${recorded.audioTracks}\n` +
        `  recorded peak  ${recorded.peak} (gate saw ${recorded.gatePeak}, measured=${recorded.measured})\n` +
        `  audio source   ${recorded.audioSource}\n` +
        `  tap rates      ${recorded.taps.join(", ") || "none"}\n` +
        `  ws audio deltas ${audioDeltaFrames} (>0 ⇒ the voice is PCM on the WebSocket)\n` +
        `  ws errors      ${wsErrors.length}${wsErrors.length ? ` — ${wsErrors[0]}` : ""}\n` +
        `  framesDecoded  ${stats.framesDecoded}\n  totalAudioEnergy ${stats.audioEnergy}\n`,
    );

    // The file has to contain a moving picture AND a voice; a silent idle animation answers nothing.
    expect(recorded.videoTracks).toBeGreaterThan(0);
    expect(fs.statSync(file).size).toBeGreaterThan(100_000);
    expect(audible, "the avatar never became audible — the recording would show an idle face").toBe(
      true,
    );
    // The level measured ON the recording, not a counter read afterwards from a connection that may
    // have been rebuilt in the meantime — that read returned 0 on a take whose audio was fine.
    expect(recorded.peak, "the captured audio was silent").toBeGreaterThan(0.01);
  });
});
